"""
Internationalization support for Big Hardware Info.

Provides gettext-based translation support.
The actual .po/.mo files are generated by CI/CD automation.
"""

import gettext
import locale
import os
from pathlib import Path

# Application domain for translations
APP_DOMAIN = "big-hardware-info"

# Default locale directory (will be set during package installation)
# The CI/CD will generate .mo files in /usr/share/locale/
LOCALE_DIR = "/usr/share/locale"

# Fallback to local development locale directory
DEV_LOCALE_DIR = Path(__file__).parent.parent.parent / "locale"


def setup_i18n() -> gettext.GNUTranslations:
    """
    Initialize internationalization support.
    
    Returns:
        Translation object for the application.
    """
    # Try to get system locale
    try:
        locale.setlocale(locale.LC_ALL, "")
    except locale.Error:
        pass
    
    # Determine locale directory
    locale_dir = LOCALE_DIR
    if DEV_LOCALE_DIR.exists():
        locale_dir = str(DEV_LOCALE_DIR)
    
    # Get translation object
    try:
        translation = gettext.translation(
            APP_DOMAIN,
            localedir=locale_dir,
            fallback=True
        )
    except Exception:
        # Fallback to NullTranslations if no translations found
        translation = gettext.NullTranslations()
    
    return translation


# Initialize translation on module load
_translation = setup_i18n()

# Main translation function - use this for all translatable strings
_ = _translation.gettext

# Ngettext for plural forms
ngettext = _translation.ngettext


def get_translator():
    """
    Get the translation function.
    
    Returns:
        The gettext function for translating strings.
    """
    return _


def refresh_translations():
    """
    Refresh translations (e.g., after locale change).
    """
    global _translation, _, ngettext
    _translation = setup_i18n()
    _ = _translation.gettext
    ngettext = _translation.ngettext
